apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: blue
  template:
    metadata:
      labels:
        app: app
        version: blue
    spec:
      containers:
      - name: app
        image: udaypagidimari/bankapp:REPLACE_TAG  # Replace with your Blue version image
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "mysql"  # MySQL service name
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "test_db"
        ports:
        - containerPort: 5000
